import type { App } from "../app/App";

export interface PluginContext {
  app: App;
  config: App["config"];
  pluginData: App["pluginData"];
  diagnostics: App["diagnostics"];
  shell: App["shell"];
  desktopMain: App["desktopMain"];
  vaults: App["vaults"];
  revisions: App["revisions"];
  fileRecovery: App["fileRecovery"];
  themeMarketplace: App["themeMarketplace"];
  themeInstaller: App["themeInstaller"];
  buildPipeline: App["buildPipeline"];
  releases: App["releases"];
  pluginPackager: App["pluginPackager"];
  themePackager: App["themePackager"];
  propertyRegistry: App["propertyRegistry"];
  properties: App["properties"];
  devtools: App["devtools"];
  workspaceLayouts: App["workspaceLayouts"];
  lifecycle: App["lifecycle"];
  workspace: App["workspace"];
  vault: App["vault"];
  metadataCache: App["metadataCache"];
  linkGraph: App["linkGraph"];
  tagIndex: App["tagIndex"];
  search: App["search"];
  menus: App["menus"];
  fileManager: App["fileManager"];
  commands: App["commands"];
  themes: App["themes"];
  customCss: App["customCss"];
  cssSnippets: App["cssSnippets"];
  appearance: App["appearance"];
  internalPlugins: App["internalPlugins"];
  communityPlugins: App["communityPlugins"];
  pluginMarketplace: App["pluginMarketplace"];
  pluginSecurity: App["pluginSecurity"];
  pluginInstaller: App["pluginInstaller"];
  updates: App["updates"];
  fileWatcher: App["fileWatcher"];
  settingSections: App["settingSections"];
  dragManager: App["dragManager"];
  uriRouter: App["uriRouter"];
  windowManager: App["windowManager"];
  popoutManager: App["popoutManager"];
  mobileWorkspace: App["mobileWorkspace"];
  hoverPreview: App["hoverPreview"];
  hotkeys: App["hotkeys"];
  pluginLoader: App["pluginLoader"];
}

export function createPluginContext(app: App): PluginContext {
  return {
    app,
    config: app.config,
    pluginData: app.pluginData,
    diagnostics: app.diagnostics,
    shell: app.shell,
    desktopMain: app.desktopMain,
    vaults: app.vaults,
    revisions: app.revisions,
    fileRecovery: app.fileRecovery,
    themeMarketplace: app.themeMarketplace,
    themeInstaller: app.themeInstaller,
    buildPipeline: app.buildPipeline,
    releases: app.releases,
    pluginPackager: app.pluginPackager,
    themePackager: app.themePackager,
    propertyRegistry: app.propertyRegistry,
    properties: app.properties,
    devtools: app.devtools,
    workspaceLayouts: app.workspaceLayouts,
    lifecycle: app.lifecycle,
    workspace: app.workspace,
    vault: app.vault,
    metadataCache: app.metadataCache,
    linkGraph: app.linkGraph,
    tagIndex: app.tagIndex,
    search: app.search,
    menus: app.menus,
    fileManager: app.fileManager,
    commands: app.commands,
    themes: app.themes,
    customCss: app.customCss,
    cssSnippets: app.cssSnippets,
    appearance: app.appearance,
    internalPlugins: app.internalPlugins,
    communityPlugins: app.communityPlugins,
    pluginMarketplace: app.pluginMarketplace,
    pluginSecurity: app.pluginSecurity,
    pluginInstaller: app.pluginInstaller,
    updates: app.updates,
    fileWatcher: app.fileWatcher,
    settingSections: app.settingSections,
    dragManager: app.dragManager,
    uriRouter: app.uriRouter,
    windowManager: app.windowManager,
    popoutManager: app.popoutManager,
    mobileWorkspace: app.mobileWorkspace,
    hoverPreview: app.hoverPreview,
    hotkeys: app.hotkeys,
    pluginLoader: app.pluginLoader,
  };
}
