// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blobs.sql

package sqlc

import (
	"context"
)

const getBlob = `-- name: GetBlob :one
SELECT bytes FROM blobs
WHERE vault_id = $1 AND hash = $2
`

type GetBlobParams struct {
	VaultID string `json:"vault_id"`
	Hash    string `json:"hash"`
}

func (q *Queries) GetBlob(ctx context.Context, arg GetBlobParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getBlob, arg.VaultID, arg.Hash)
	var bytes []byte
	err := row.Scan(&bytes)
	return bytes, err
}

const hasBlob = `-- name: HasBlob :one
SELECT EXISTS (
    SELECT 1 FROM blobs WHERE vault_id = $1 AND hash = $2
)
`

type HasBlobParams struct {
	VaultID string `json:"vault_id"`
	Hash    string `json:"hash"`
}

func (q *Queries) HasBlob(ctx context.Context, arg HasBlobParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasBlob, arg.VaultID, arg.Hash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const putBlob = `-- name: PutBlob :exec
INSERT INTO blobs (vault_id, hash, bytes, size)
VALUES ($1, $2, $3, $4)
ON CONFLICT (vault_id, hash) DO NOTHING
`

type PutBlobParams struct {
	VaultID string `json:"vault_id"`
	Hash    string `json:"hash"`
	Bytes   []byte `json:"bytes"`
	Size    int64  `json:"size"`
}

func (q *Queries) PutBlob(ctx context.Context, arg PutBlobParams) error {
	_, err := q.db.Exec(ctx, putBlob,
		arg.VaultID,
		arg.Hash,
		arg.Bytes,
		arg.Size,
	)
	return err
}
