// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type VaultRole string

const (
	VaultRoleOwner  VaultRole = "owner"
	VaultRoleEditor VaultRole = "editor"
)

func (e *VaultRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VaultRole(s)
	case string:
		*e = VaultRole(s)
	default:
		return fmt.Errorf("unsupported scan type for VaultRole: %T", src)
	}
	return nil
}

type NullVaultRole struct {
	VaultRole VaultRole `json:"vault_role"`
	Valid     bool      `json:"valid"` // Valid is true if VaultRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVaultRole) Scan(value interface{}) error {
	if value == nil {
		ns.VaultRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VaultRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVaultRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VaultRole), nil
}

type Blob struct {
	VaultID   string             `json:"vault_id"`
	Hash      string             `json:"hash"`
	Bytes     []byte             `json:"bytes"`
	Size      int64              `json:"size"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Room struct {
	VaultID    string             `json:"vault_id"`
	RoomID     string             `json:"room_id"`
	CrdtType   int16              `json:"crdt_type"`
	Snapshot   []byte             `json:"snapshot"`
	SnapshotAt pgtype.Timestamptz `json:"snapshot_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RoomLog struct {
	VaultID    string             `json:"vault_id"`
	RoomID     string             `json:"room_id"`
	CrdtType   int16              `json:"crdt_type"`
	N          int64              `json:"n"`
	Bytes      []byte             `json:"bytes"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

type User struct {
	ID        string             `json:"id"`
	Email     string             `json:"email"`
	PassHash  string             `json:"pass_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Vault struct {
	ID        string             `json:"id"`
	OwnerID   string             `json:"owner_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type VaultMember struct {
	VaultID string `json:"vault_id"`
	UserID  string `json:"user_id"`
	Role    string `json:"role"`
}
