// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package sqlc

import (
	"context"
)

const appendRoomLog = `-- name: AppendRoomLog :one
INSERT INTO room_log (vault_id, room_id, crdt_type, n, bytes)
VALUES (
    $1, $2, $3,
    (
        SELECT COALESCE(MAX(n), 0) + 1 FROM room_log
        WHERE vault_id = $1 AND room_id = $2 AND crdt_type = $3
    ),
    $4
)
RETURNING n
`

type AppendRoomLogParams struct {
	VaultID  string `json:"vault_id"`
	RoomID   string `json:"room_id"`
	CrdtType int16  `json:"crdt_type"`
	Bytes    []byte `json:"bytes"`
}

func (q *Queries) AppendRoomLog(ctx context.Context, arg AppendRoomLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, appendRoomLog,
		arg.VaultID,
		arg.RoomID,
		arg.CrdtType,
		arg.Bytes,
	)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const deleteRoomLogThrough = `-- name: DeleteRoomLogThrough :execrows
DELETE FROM room_log
WHERE vault_id = $1 AND room_id = $2 AND crdt_type = $3 AND n <= $4
`

type DeleteRoomLogThroughParams struct {
	VaultID  string `json:"vault_id"`
	RoomID   string `json:"room_id"`
	CrdtType int16  `json:"crdt_type"`
	N        int64  `json:"n"`
}

func (q *Queries) DeleteRoomLogThrough(ctx context.Context, arg DeleteRoomLogThroughParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoomLogThrough,
		arg.VaultID,
		arg.RoomID,
		arg.CrdtType,
		arg.N,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRoom = `-- name: GetRoom :one
SELECT vault_id, room_id, crdt_type, snapshot, snapshot_at, created_at FROM rooms
WHERE vault_id = $1 AND room_id = $2 AND crdt_type = $3
`

type GetRoomParams struct {
	VaultID  string `json:"vault_id"`
	RoomID   string `json:"room_id"`
	CrdtType int16  `json:"crdt_type"`
}

func (q *Queries) GetRoom(ctx context.Context, arg GetRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, arg.VaultID, arg.RoomID, arg.CrdtType)
	var i Room
	err := row.Scan(
		&i.VaultID,
		&i.RoomID,
		&i.CrdtType,
		&i.Snapshot,
		&i.SnapshotAt,
		&i.CreatedAt,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT room_id, crdt_type FROM rooms
WHERE vault_id = $1
ORDER BY room_id, crdt_type
`

type ListRoomsRow struct {
	RoomID   string `json:"room_id"`
	CrdtType int16  `json:"crdt_type"`
}

func (q *Queries) ListRooms(ctx context.Context, vaultID string) ([]ListRoomsRow, error) {
	rows, err := q.db.Query(ctx, listRooms, vaultID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomsRow
	for rows.Next() {
		var i ListRoomsRow
		if err := rows.Scan(&i.RoomID, &i.CrdtType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRoom = `-- name: LockRoom :one
SELECT 1 FROM rooms
WHERE vault_id = $1 AND room_id = $2 AND crdt_type = $3
FOR UPDATE
`

type LockRoomParams struct {
	VaultID  string `json:"vault_id"`
	RoomID   string `json:"room_id"`
	CrdtType int16  `json:"crdt_type"`
}

// The room row is the append lock: callers take it inside a transaction
// before assigning the next n. :one so a missing room surfaces as
// ErrNoRows — an Exec would swallow the zero-row case silently.
func (q *Queries) LockRoom(ctx context.Context, arg LockRoomParams) (int32, error) {
	row := q.db.QueryRow(ctx, lockRoom, arg.VaultID, arg.RoomID, arg.CrdtType)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const scanRoomLog = `-- name: ScanRoomLog :many
SELECT n, bytes FROM room_log
WHERE vault_id = $1 AND room_id = $2 AND crdt_type = $3 AND n > $4
ORDER BY n
`

type ScanRoomLogParams struct {
	VaultID  string `json:"vault_id"`
	RoomID   string `json:"room_id"`
	CrdtType int16  `json:"crdt_type"`
	N        int64  `json:"n"`
}

type ScanRoomLogRow struct {
	N     int64  `json:"n"`
	Bytes []byte `json:"bytes"`
}

func (q *Queries) ScanRoomLog(ctx context.Context, arg ScanRoomLogParams) ([]ScanRoomLogRow, error) {
	rows, err := q.db.Query(ctx, scanRoomLog,
		arg.VaultID,
		arg.RoomID,
		arg.CrdtType,
		arg.N,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanRoomLogRow
	for rows.Next() {
		var i ScanRoomLogRow
		if err := rows.Scan(&i.N, &i.Bytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRoomSnapshot = `-- name: SetRoomSnapshot :exec
UPDATE rooms
SET snapshot = $4, snapshot_at = now()
WHERE vault_id = $1 AND room_id = $2 AND crdt_type = $3
`

type SetRoomSnapshotParams struct {
	VaultID  string `json:"vault_id"`
	RoomID   string `json:"room_id"`
	CrdtType int16  `json:"crdt_type"`
	Snapshot []byte `json:"snapshot"`
}

func (q *Queries) SetRoomSnapshot(ctx context.Context, arg SetRoomSnapshotParams) error {
	_, err := q.db.Exec(ctx, setRoomSnapshot,
		arg.VaultID,
		arg.RoomID,
		arg.CrdtType,
		arg.Snapshot,
	)
	return err
}

const upsertRoom = `-- name: UpsertRoom :exec
INSERT INTO rooms (vault_id, room_id, crdt_type)
VALUES ($1, $2, $3)
ON CONFLICT (vault_id, room_id, crdt_type) DO NOTHING
`

type UpsertRoomParams struct {
	VaultID  string `json:"vault_id"`
	RoomID   string `json:"room_id"`
	CrdtType int16  `json:"crdt_type"`
}

func (q *Queries) UpsertRoom(ctx context.Context, arg UpsertRoomParams) error {
	_, err := q.db.Exec(ctx, upsertRoom, arg.VaultID, arg.RoomID, arg.CrdtType)
	return err
}
