// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vaults.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addVaultMember = `-- name: AddVaultMember :exec
INSERT INTO vault_members (vault_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (vault_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddVaultMemberParams struct {
	VaultID string `json:"vault_id"`
	UserID  string `json:"user_id"`
	Role    string `json:"role"`
}

func (q *Queries) AddVaultMember(ctx context.Context, arg AddVaultMemberParams) error {
	_, err := q.db.Exec(ctx, addVaultMember, arg.VaultID, arg.UserID, arg.Role)
	return err
}

const createVault = `-- name: CreateVault :one
INSERT INTO vaults (owner_id, name)
VALUES ($1, $2)
RETURNING id, owner_id, name, created_at
`

type CreateVaultParams struct {
	OwnerID string `json:"owner_id"`
	Name    string `json:"name"`
}

func (q *Queries) CreateVault(ctx context.Context, arg CreateVaultParams) (Vault, error) {
	row := q.db.QueryRow(ctx, createVault, arg.OwnerID, arg.Name)
	var i Vault
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getVaultMember = `-- name: GetVaultMember :one
SELECT role FROM vault_members
WHERE vault_id = $1 AND user_id = $2
`

type GetVaultMemberParams struct {
	VaultID string `json:"vault_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) GetVaultMember(ctx context.Context, arg GetVaultMemberParams) (string, error) {
	row := q.db.QueryRow(ctx, getVaultMember, arg.VaultID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listVaultsForUser = `-- name: ListVaultsForUser :many
SELECT v.id, v.owner_id, v.name, v.created_at, m.role FROM vaults v
JOIN vault_members m ON m.vault_id = v.id
WHERE m.user_id = $1
ORDER BY v.created_at
`

type ListVaultsForUserRow struct {
	ID        string             `json:"id"`
	OwnerID   string             `json:"owner_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Role      string             `json:"role"`
}

func (q *Queries) ListVaultsForUser(ctx context.Context, userID string) ([]ListVaultsForUserRow, error) {
	rows, err := q.db.Query(ctx, listVaultsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVaultsForUserRow
	for rows.Next() {
		var i ListVaultsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
